### ISSUE TITLE
iOS?

### ISSUE THREAD

**Issue by bpolonia** [Haargeeel/react-native-wifi-checker#1]
Hi, is this working for iOS? I'm trying it and can't get it to work. Wasn't sure by what you wrote for the iOS instructions. lol 😄

**Comment by Haargeeel** [comment]
Yeah sorry. I never got around to learn this little bit of ObjectiveC to implement it. So for unforeseeable future it is Android only.

**Comment by bpolonia** [comment]
I'm working on something where I'll need it to work on both. I might be able to get it working with swift. If I do I'll submit a PR.

Thanks! 👍
